In [11]:
import torch
from torch import nn
torch.manual_seed(0)
torch.cuda.manual_seed_all(0)

# loss_fn

In [12]:
loss_fn = nn.CrossEntropyLoss()

# x

In [13]:
x = torch.randn(5, 5)
x

tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487],
        [ 0.6920, -0.3160, -2.1152,  0.3223, -0.1577],
        [ 1.4437,  0.2660,  0.1665,  0.8744, -0.1435],
        [-0.1116, -0.6136,  1.2590,  2.0050,  0.0537],
        [ 0.6181, -0.4128, -0.8411, -2.3160, -0.1023]])

# 2种y

## 指定下标为y

In [14]:
y1 = torch.arange(len(x))
y1

tensor([0, 1, 2, 3, 4])

## 对焦矩阵为y

In [15]:
y2 = torch.eye(len(x))
y2

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# loss结果相同

In [16]:
loss_fn(x, y1)

tensor(1.7507)

In [17]:
loss_fn(x, y2)

tensor(1.7507)